services:
  - type: web
    name: foottournoi-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: node server/server.cjs
    envVars:
      - key: DATABASE_URL
        value: postgresql://foottournoi_user:0yngVcb7JJtLGGD55M1oCU3y7Bxsh7pu@dpg-cvs73pq4d50c7389d520-a.oregon-postgres.render.com/foottournoi
      - key: JWT_SECRET
        value: votre_cle_secrete_complexe

  - type: web
    name: foottournoi-frontend
    env: node
    buildCommand: cd client && npm install && npm run build
    staticPublish: client/dist
    envVars:
      - key: VITE_API_URL
        value: [https://foottournoi-backend.onrender.com](https://foottournoi-backend.onrender.com)